name: "TangleGuard Linter (Beta)"
description: "Runs TangleGuard CLI to detect architecture drift"
author: "Jan Arends"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Download TangleGuard CLI
      shell: bash
      run: |
        echo "Downloading TangleGuard CLI..."
        if ! curl -L -o tangleguard-cli https://nbg1.your-objectstorage.com/tangleguard/releases/latest/tangleguard-cli; then
          echo "❌ Failed to download TangleGuard CLI"
          exit 1
        fi

        echo "Making it executable..."
        chmod +x tangleguard-cli

        echo "Verifying download..."
        if [[ ! -x "./tangleguard-cli" ]]; then
          echo "❌ TangleGuard CLI is not executable"
          exit 1
        fi

        echo "✅ TangleGuard CLI downloaded successfully"
        ./tangleguard-cli --help | head -3

    - name: Run TangleGuard validation
      shell: bash
      # working-directory: ${{ inputs.working_directory }}
      run: |
        echo "🔍 Running TangleGuard validation..."
        if ./tangleguard-cli validate-all; then
          echo "✅ TangleGuard validation passed"
        else
          exit_code=$?
          if [[ $exit_code -eq 1 ]]; then
            echo "❌ TangleGuard found architecture violations"
          else
            echo "❌ TangleGuard validation failed with error (exit code: $exit_code)"
          fi
          exit $exit_code
        fi
      id: cli_execution

branding:
  icon: "layers"
  color: "gray-dark"
