name: "TangleGuard (Beta)"
description: "Abstracts your codebase into an interactive dependency graph diagram for architectural analysis."
author: "Jan Arends"
inputs:
  upload_results:
    description: "Whether to upload scan results to TangleGuard Cloud or not (must be true - no other option available in evaluation phase)"
    required: true
  make_public:
    description: "Whether to make scan results publicly available (must be true - private scan results are not yet supported)"
    required: true
  repository:
    description: "Repository in format 'owner/project' (optional, will be extracted from Git if not provided)"
    required: false
  description:
    description: "Project description for uploaded results (required for better project identification on website)"
    required: true
  language:
    description: "Programming language (rust|javascript)"
    required: true
  path:
    description: "Path to the workspace to analyze (defaults to current directory)"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Validate input parameters
      shell: bash
      run: |
        echo "🔍 Validating input parameters..."

        if [[ "${{ inputs.upload_results }}" != "true" ]]; then
          echo "❌ Error: upload_results must be set to 'true'. This is currently the only supported option in the evaluation phase."
          echo "   Scan results will be uploaded to TangleGuard Cloud as this is an open-source evaluation."
          exit 1
        fi

        if [[ "${{ inputs.make_public }}" != "true" ]]; then
          echo "❌ Error: Private scan results are not yet supported."
          echo "   Please set make_public to 'true' to continue with public scan results."
          exit 1
        fi

        if [[ -z "${{ inputs.description }}" ]]; then
          echo "❌ Error: description is required."
          echo "   Please provide a project description for better identification on the website."
          exit 1
        fi

        echo "✅ Input validation passed"

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Download TangleGuard CLI
      shell: bash
      run: |
        echo "Downloading TangleGuard CLI..."
        if ! curl -L -o tangleguard-cli https://tangleguard-builds.s3.eu-central-1.amazonaws.com/cli/latest/tangleguard-cli; then
          echo "❌ Failed to download TangleGuard CLI"
          exit 1
        fi

        echo "Making it executable..."
        chmod +x tangleguard-cli

        echo "Verifying download..."
        if [[ ! -x "./tangleguard-cli" ]]; then
          echo "❌ TangleGuard CLI is not executable"
          exit 1
        fi
        echo "✅ TangleGuard CLI downloaded"

    # Validation is currently under construction and available again soon
    # - name: Run TangleGuard validation
    #   shell: bash
    #   run: |
    #     echo "🔍 Running TangleGuard validation..."
    #     if ./tangleguard-cli -l ${{ inputs.language }} -p ${{ inputs.path }} validate; then
    #       echo "✅ TangleGuard validation passed"
    #     else
    #       exit_code=$?
    #       if [[ $exit_code -eq 1 ]]; then
    #         echo "❌ TangleGuard found architecture violations"
    #       else
    #         echo "❌ TangleGuard validation failed with error (exit code: $exit_code)"
    #       fi
    #       if [[ "${{ inputs.fail_on_findings }}" == "true" ]]; then
    #         exit $exit_code
    #       fi
    #     fi
    #   id: cli_execution

    - name: Upload results to TangleGuard Cloud
      shell: bash
      if: ${{ inputs.upload_results == 'true' }}
      run: |
        echo "Scanning workspace and uploading results to TangleGuard Cloud..."

        # Scan and upload results
        upload_cmd="./tangleguard-cli --language ${{ inputs.language }}"
        
        # Add path if specified (default is current directory)
        if [[ -n "${{ inputs.path }}" ]]; then
          upload_cmd="$upload_cmd --path ${{ inputs.path }}"
        fi
        
        # Add upload subcommand
        upload_cmd="$upload_cmd upload"
        
        # Add upload subcommand arguments
        if [[ -n "${{ inputs.description }}" ]]; then
          upload_cmd="$upload_cmd --description \"${{ inputs.description }}\""
        fi
        
        if [[ -n "${{ inputs.repository }}" ]]; then
          upload_cmd="$upload_cmd --repository \"${{ inputs.repository }}\""
        fi

        eval $upload_cmd

branding:
  icon: "layers"
  color: "gray-dark"
