name: "TangleGuard (Beta)"
description: "Abstracts your codebase into an interactive dependency graph diagram for architectural analysis."
author: "Jan Arends"
inputs:
  path:
    description: "Path to scan"
    required: false
    default: "."
  upload_results:
    description: "Upload scan results to TangleGuard server"
    required: true
  repository:
    description: "Repository in format 'owner/project' (optional, will be extracted from Git if not provided)"
    required: false
  description:
    description: "Project description for uploaded results (optional, will be extracted from Git if not provided)"
    required: false
  language:
    description: "Programming language (rust|javascript)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Download TangleGuard CLI
      shell: bash
      run: |
        echo "Downloading TangleGuard CLI..."
        if ! curl -L -o tangleguard-cli https://tangleguard-builds.s3.eu-central-1.amazonaws.com/cli/latest/tangleguard-cli; then
          echo "❌ Failed to download TangleGuard CLI"
          exit 1
        fi

        echo "Making it executable..."
        chmod +x tangleguard-cli

        echo "Verifying download..."
        if [[ ! -x "./tangleguard-cli" ]]; then
          echo "❌ TangleGuard CLI is not executable"
          exit 1
        fi
        echo "✅ TangleGuard CLI downloaded"

    # Validation is currently under construction and available again soon
    # - name: Run TangleGuard validation
    #   shell: bash
    #   run: |
    #     echo "🔍 Running TangleGuard validation..."
    #     if ./tangleguard-cli -l ${{ inputs.language }} -p ${{ inputs.path }} validate; then
    #       echo "✅ TangleGuard validation passed"
    #     else
    #       exit_code=$?
    #       if [[ $exit_code -eq 1 ]]; then
    #         echo "❌ TangleGuard found architecture violations"
    #       else
    #         echo "❌ TangleGuard validation failed with error (exit code: $exit_code)"
    #       fi
    #       if [[ "${{ inputs.fail_on_findings }}" == "true" ]]; then
    #         exit $exit_code
    #       fi
    #     fi
    #   id: cli_execution

    - name: Upload results to TangleGuard Cloud
      shell: bash
      if: ${{ inputs.upload_results == 'true' }}
      run: |
        echo "Scanning workspace and uploading results to TangleGuard Cloud..."

        # Scan and upload results
        upload_cmd="./tangleguard-cli --language ${{ inputs.language }} --path ${{ inputs.path }} upload"

        if [[ -n "${{ inputs.description }}" ]]; then
          upload_cmd="$upload_cmd --description \"${{ inputs.description }}\""
        fi

        eval $upload_cmd

branding:
  icon: "layers"
  color: "gray-dark"
